import 'package:flutter/material.dart';

const kName = 'RepoMed';
const kLogo1 = 'assets/images/logo1.png';
const kLogo2 = 'assets/images/logo2.png';
const kLogo3 = 'assets/images/logo3.png';
const kPrimaryColor = Color(0xff132E59);
const kSecondColor = Color(0xffabdbe3);
const kSecondColor2 = Color(0xff26577C);
const kThirdColor = Color(0xffeeeee4);
const kThirdColor2 = Color(0xffF8F0E5);
const kLogoColor1 = Color(0xff132E59);
const kLogoColor2 = Color(0xff7fccef);
const kLogoColor3 = Color(0xff3969bc);
const kLogoColor4 = Color(0xff5cc1ef);
const kFont1 = 'pacifico';
const kFont2 = 'Poppins';
const kToken = 'token';
const kToken1 = 'token';
const kOrderBox = 'orders box';
